(function() {var implementors = {
"jf_aead":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"jf_aead/struct.AEADError.html\" title=\"struct jf_aead::AEADError\">AEADError</a>"]],
"jf_elgamal":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"jf_elgamal/struct.ParameterError.html\" title=\"struct jf_elgamal::ParameterError\">ParameterError</a>"]],
"jf_merkle_tree":[["impl&lt;H&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"jf_merkle_tree/hasher/struct.HasherNode.html\" title=\"struct jf_merkle_tree::hasher::HasherNode\">HasherNode</a>&lt;H&gt;<div class=\"where\">where\n    H: Digest,</div>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"jf_merkle_tree/errors/enum.MerkleTreeError.html\" title=\"enum jf_merkle_tree::errors::MerkleTreeError\">MerkleTreeError</a>"]],
"jf_pcs":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"jf_pcs/transcript/enum.TranscriptError.html\" title=\"enum jf_pcs::transcript::TranscriptError\">TranscriptError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"jf_pcs/errors/enum.PCSError.html\" title=\"enum jf_pcs::errors::PCSError\">PCSError</a>"]],
"jf_plonk":[["impl&lt;E: Pairing&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"jf_plonk/proof_system/structs/struct.Proof.html\" title=\"struct jf_plonk::proof_system::structs::Proof\">Proof</a>&lt;E&gt;"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"jf_plonk/errors/enum.PlonkError.html\" title=\"enum jf_plonk::errors::PlonkError\">PlonkError</a>"],["impl&lt;E: Pairing&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"jf_plonk/proof_system/structs/struct.BatchProof.html\" title=\"struct jf_plonk::proof_system::structs::BatchProof\">BatchProof</a>&lt;E&gt;"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"jf_plonk/errors/enum.SnarkError.html\" title=\"enum jf_plonk::errors::SnarkError\">SnarkError</a>"]],
"jf_relation":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"jf_relation/enum.CircuitError.html\" title=\"enum jf_relation::CircuitError\">CircuitError</a>"]],
"jf_rescue":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"jf_rescue/enum.RescueError.html\" title=\"enum jf_rescue::RescueError\">RescueError</a>"]],
"jf_signature":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"jf_signature/enum.SignatureError.html\" title=\"enum jf_signature::SignatureError\">SignatureError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"jf_signature/bls_over_bls12381/struct.BLSSignature.html\" title=\"struct jf_signature::bls_over_bls12381::BLSSignature\">BLSSignature</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"jf_signature/bls_over_bls12381/struct.BLSSignKey.html\" title=\"struct jf_signature::bls_over_bls12381::BLSSignKey\">BLSSignKey</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"jf_signature/bls_over_bn254/struct.Signature.html\" title=\"struct jf_signature::bls_over_bn254::Signature\">Signature</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"jf_signature/bls_over_bn254/struct.VerKey.html\" title=\"struct jf_signature::bls_over_bn254::VerKey\">VerKey</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"jf_signature/bls_over_bn254/struct.SignKey.html\" title=\"struct jf_signature::bls_over_bn254::SignKey\">SignKey</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"jf_signature/bls_over_bls12381/struct.BLSVerKey.html\" title=\"struct jf_signature::bls_over_bls12381::BLSVerKey\">BLSVerKey</a>"]],
"jf_utils":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"jf_utils/reed_solomon_code/struct.RSCodeError.html\" title=\"struct jf_utils::reed_solomon_code::RSCodeError\">RSCodeError</a>"]],
"jf_vdf":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"jf_vdf/struct.VDFError.html\" title=\"struct jf_vdf::VDFError\">VDFError</a>"]],
"jf_vid":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"jf_vid/enum.VidError.html\" title=\"enum jf_vid::VidError\">VidError</a>"]],
"jf_vrf":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.77.2/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"jf_vrf/blsvrf/struct.BLSVRFError.html\" title=\"struct jf_vrf::blsvrf::BLSVRFError\">BLSVRFError</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()