[package]
name = "jf-rescue"
description = "Rescue hash function"
version = "0.1.2"
authors = ["Espresso Systems <hello@espressosys.com>"]
edition = "2018"
license = "MIT"

[dependencies]

# ark
ark-ff = "0.3.0"
ark-std = { version = "0.3.0", default-features = false }
ark-ec = "0.3.0"
ark-serialize = "0.3.0"

# ark cruves
ark-ed-on-bls12-377 = { git = "https://github.com/arkworks-rs/curves", rev = "677b4ae751a274037880ede86e9b6f30f62635af"}
ark-ed-on-bls12-381 = "0.3.0"
ark-ed-on-bn254 = "0.3.0"
ark-bls12-377 = { git = "https://github.com/arkworks-rs/curves", rev = "677b4ae751a274037880ede86e9b6f30f62635af" }
ark-bls12-381 = "0.3.0"
ark-bn254 = "0.3.0"
ark-bw6-761 = { git = "https://github.com/arkworks-rs/curves", rev = "677b4ae751a274037880ede86e9b6f30f62635af" }

# jellyfish
jf-utils = { path = "../utilities" }

# others
zeroize = { version = "1.3", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
generic-array = { version = "^0.14", default-features = false }
displaydoc = { version = "0.2.3", default-features = false }
derivative = { version = "2", features = ["use_core"] }

[dev-dependencies]
rand_chacha = "^0.3"
bincode = "1.0"
quickcheck = "1.0.0"
criterion = "0.3.1"

[features]
default = []
std = []
