[package]
name = "jf-merkle-tree"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }

[dependencies]
ark-bls12-377 = { workspace = true }
ark-bls12-381 = { workspace = true }
ark-bn254 = { workspace = true }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-serialize = { workspace = true }
ark-std = { workspace = true }
derivative = { workspace = true }
digest = { workspace = true }
displaydoc = { workspace = true }
hashbrown = { workspace = true }
itertools = { workspace = true }
jf-primitives-core = { path = "../core", default-features = false }
jf-relation = { path = "../relation", optional = true, default-features = false }
jf-rescue = { path = "../rescue", default-features = false }
jf-utils = { path = "../utilities", default-features = false }
num-bigint = { workspace = true }
num-traits = { version = "0.2.15", default-features = false }
serde = { workspace = true }
sha3 = { workspace = true }
tagged-base64 = { workspace = true }

[dev-dependencies]
ark-ed-on-bls12-377 = "0.4.0"
ark-ed-on-bls12-381 = "0.4.0"
ark-ed-on-bn254 = "0.4.0"
bincode = "1.3"
criterion = "0.5.1"
sha2 = { workspace = true }

[[bench]]
name = "merkle_path"
harness = false

[features]
default = []
std = [
        "ark-bls12-377/std",
        "ark-bls12-381/std",
        "ark-bn254/std",
        "ark-std/std",
        "ark-serialize/std",
        "ark-ff/std",
        "num-bigint/std",
        "num-traits/std",
        "sha3/std",
        "itertools/use_std",
        "jf-utils/std",
        "jf-relation/std",
        "jf-primitives-core/std",
]
gadgets = [
    "jf-relation",
    "jf-rescue/gadgets",
]
