(function() {var implementors = {
"jf_aead":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"jf_aead/struct.AEADError.html\" title=\"struct jf_aead::AEADError\">AEADError</a>"]],
"jf_merkle_tree":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"jf_merkle_tree/errors/enum.MerkleTreeError.html\" title=\"enum jf_merkle_tree::errors::MerkleTreeError\">MerkleTreeError</a>"]],
"jf_pcs":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"jf_pcs/errors/enum.PCSError.html\" title=\"enum jf_pcs::errors::PCSError\">PCSError</a>"]],
"jf_plonk":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"jf_plonk/errors/enum.PlonkError.html\" title=\"enum jf_plonk::errors::PlonkError\">PlonkError</a>"]],
"jf_relation":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"jf_relation/enum.CircuitError.html\" title=\"enum jf_relation::CircuitError\">CircuitError</a>"]],
"jf_rescue":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"jf_rescue/enum.RescueError.html\" title=\"enum jf_rescue::RescueError\">RescueError</a>"]],
"jf_signature":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"jf_signature/enum.SignatureError.html\" title=\"enum jf_signature::SignatureError\">SignatureError</a>"]],
"jf_utils":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"jf_utils/reed_solomon_code/struct.RSCodeError.html\" title=\"struct jf_utils::reed_solomon_code::RSCodeError\">RSCodeError</a>"]],
"jf_vid":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"jf_vid/enum.VidError.html\" title=\"enum jf_vid::VidError\">VidError</a>"]],
"jf_vrf":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"jf_vrf/blsvrf/struct.BLSVRFError.html\" title=\"struct jf_vrf::blsvrf::BLSVRFError\">BLSVRFError</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()