name: Combine PRs

on:
  schedule:
    - cron: "0 1 * * MON"
  workflow_dispatch: # allows to manually trigger the workflow

# The minimum permissions required to run this Action
permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - name: combine-prs
        id: combine-prs
        uses: github/combine-prs@v5.0.0
        with:
          github_token: ${{ secrets.ORG_GITHUB_PAT }}
          labels: "dependabot,combined-pr"
