name: Periodic code checks

on:
  schedule:
    - cron: "0 0 * * 0" # At 00:00 on Sunday.
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          default: false

      - name: Run cargo-udeps
        uses: aig787/cargo-udeps-action@v1
        with:
          # not using --all-targets because --examples need "--features test-srs"
          # checking the rest is sufficient for udeps purposes.
          args: "--workspace --tests --lib --bins --benches"
